### ISSUE TITLE
Loading Duro/TutorialD into any program as a DLL

### ISSUE THREAD

**Issue by z505** [rehartmann/durodbms#1]
Hi I am wondering if duro can be loaded in to any program as a DLL and then used. This would make it more easy to make it used widespread...

For example any language could call the durodll into its program and then make use of duro.

I'm sure you probably already thought of this and that is likely how tcl/python are able to use it. But since I do not remember/know the duro code well (I looked over it long ago) I do not know if this is possible.

If that was the case, that any language could call in a flat plain c dll and use Duro by sending tutorialD strings through a dll function, would it make sense for the library to be released under LGPL rather than GPL? If it's a gpl 2/3 dll then no one can use it unless they release all their code as gpl in their main exe/elf that calls the dll/shared object.

**Comment by rehartmann** [comment]
Yes, it is possible - the Java interface does exactly that, it loads the Duro core as a DLL and calls it using JNI. There is even a Windows binary distribution at: https://sourceforge.net/projects/duro/files/duro/1.2/

If there is a number of people who are interested in using Duro from non-GPL projects, I may consider changing the license to LGPL.

**Comment by rehartmann** [comment]
Note that changing the license to LGPL would not change that much because DuroDBMS requires Berkeley DB, and the License of Berkeley DB is the GNU AGPL which is even more restrictive than the GNU GPL.
